✅ 🐧🧹 🖳🗑️

diff --git a/misc/Github/Runners/Ubuntu/0xf_gh_runner_ubuntu_debug.yaml b/misc/Github/Runners/Ubuntu/0xf_gh_runner_ubuntu_debug.yaml
--- a/misc/Github/Runners/Ubuntu/0xf_gh_runner_ubuntu_debug.yaml
+++ b/misc/Github/Runners/Ubuntu/0xf_gh_runner_ubuntu_debug.yaml
@@ -175,7 +175,34 @@ jobs:
           nohup "$HOME/openvscode-server/bin/openvscode-server" --host "0.0.0.0" --port "8080" --telemetry-level off --accept-server-license-terms --without-connection-token >/dev/null 2>&1 &
         continue-on-error: true
         
-     #Comment, if you do not want a build/compile ready environment for rust      
+     #Comment, if you do not want a build/compile ready environment for rust
+     
+      - name: Install Nix (With Experimental Features)
+        run: |
+           # Presets
+           set -x ; set +e
+           #--------------#
+           ##Official Installers break
+           #curl -qfsSL "https://nixos.org/nix/install" | bash -s -- --no-daemon
+           #source "$HOME/.bash_profile" ; source "$HOME/.nix-profile/etc/profile.d/nix.sh" ; . "$HOME/.nix-profile/etc/profile.d/nix.sh"
+           ##https://github.com/DeterminateSystems/nix-installer
+           "/nix/nix-installer" uninstall --no-confirm 2>/dev/null
+           curl -qfsSL "https://install.determinate.systems/nix" | bash -s -- install linux --init none --no-confirm
+           #Source
+           source "/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh"
+           #Fix perms: could not set permissions on '/nix/var/nix/profiles/per-user' to 755: Operation not permitted
+           #sudo chown --recursive "$USER" "/nix"
+           sudo chown --recursive "runner" "/nix"
+           echo "root    ALL=(ALL:ALL) ALL" | sudo tee -a "/etc/sudoers"
+           #Test
+           if ! command -v nix &> /dev/null; then
+              echo -e "\n[-] nix NOT Found\n"
+              export CONTINUE="NO" && exit 1
+           else
+              nix --version && nix-channel --list && nix-channel --update
+           fi
+        continue-on-error: true
+        
       - name: Install Rust ToolChains
         run: |
            # Presets
